require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/kanbans", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Kanban. As you add validations to Kanban, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Kanban.create! valid_attributes
      get kanbans_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      kanban = Kanban.create! valid_attributes
      get kanban_url(kanban)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_kanban_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      kanban = Kanban.create! valid_attributes
      get edit_kanban_url(kanban)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Kanban" do
        expect {
          post kanbans_url, params: { kanban: valid_attributes }
        }.to change(Kanban, :count).by(1)
      end

      it "redirects to the created kanban" do
        post kanbans_url, params: { kanban: valid_attributes }
        expect(response).to redirect_to(kanban_url(Kanban.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Kanban" do
        expect {
          post kanbans_url, params: { kanban: invalid_attributes }
        }.to change(Kanban, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post kanbans_url, params: { kanban: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested kanban" do
        kanban = Kanban.create! valid_attributes
        patch kanban_url(kanban), params: { kanban: new_attributes }
        kanban.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the kanban" do
        kanban = Kanban.create! valid_attributes
        patch kanban_url(kanban), params: { kanban: new_attributes }
        kanban.reload
        expect(response).to redirect_to(kanban_url(kanban))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        kanban = Kanban.create! valid_attributes
        patch kanban_url(kanban), params: { kanban: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested kanban" do
      kanban = Kanban.create! valid_attributes
      expect {
        delete kanban_url(kanban)
      }.to change(Kanban, :count).by(-1)
    end

    it "redirects to the kanbans list" do
      kanban = Kanban.create! valid_attributes
      delete kanban_url(kanban)
      expect(response).to redirect_to(kanbans_url)
    end
  end
end
